<?php /* @var $block \HS\GeoipRedirect\Block\System\Config\Form\Field\Database\Synchronize */ ?>

<script>
require([
    'jquery',
    'prototype',
    'mage/backend/validation',
    'jquery/validate'
], function(jQuery){

    function enableSyncButton() 
    {
        Form.Element.enable('synchronize_button');
        $('synchronize_button').removeClassName('disabled');
    }

    function disableSyncButton() 
    {
        Form.Element.disable('synchronize_button');
        $('synchronize_button').addClassName('disabled');
    }

    var checkStatus = function() 
    {
        u = new Ajax.PeriodicalUpdater('', '<?php echo $block->getAjaxStatusUpdateUrl() ?>', {
            method:     'get',
            frequency:  5,
            loaderArea: false,

            onSuccess: function(transport) {
                var response;
                
                try {
                    var percent = parseInt(transport.responseText);
                    if (percent == 100) {
                        u.stop();
                        $('sync_span').addClassName('no-display');
                        enableSyncButton();
                    } else {
                        $('sync_message_span').update(percent + '%');
                    }
                } catch (e) { }                
            }
        });
    };

    Event.observe(window, 'load', function(){
        checkStatus();
    });

    jQuery('#synchronize_button').click(function () {
        if ( ! jQuery.validator.validateElement('#synchronize-validation-input')) {
            jQuery('[for="synchronize-validation-input"]').hide();
        }

        new Ajax.Request('<?php echo $block->getAjaxSyncUrl() ?>', {
            loaderArea:     false,
            asynchronous:   true
        });

        window.setTimeout(checkStatus, 2011);
        disableSyncButton();
    });
});
</script>

<?php echo $block->getButtonHtml() ?>
<span class="sync-indicator no-display" id="sync_span">
    <img alt="Synchronize" style="margin:0 5px" src="<?php echo $block->getViewFileUrl('images/process_spinner.gif') ?>"/>
    <span id="sync_message_span"></span>
</span>
<input type="hidden" id="synchronize-validation-input" class="required-synchronize no-display"/>
